<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-M4N4JHAP" ignored="0" name="HomePage" tests="43" failures="35" timestamp="2021-03-12T21:33:47 GMT" time="253.973" errors="0">
  <testcase name="AddAscendRangeAndDescendRange" time="5.78" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [80235] but found [95672.5000000001]">
      <![CDATA[java.lang.AssertionError: expected [80235] but found [95672.5000000001]
at Acacemy.additionTest.AddAscendRangeAndDescendRange(additionTest.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddAscendRangeAndDescendRange -->
  <testcase name="AddBracketsFiveAndTwo" time="5.243" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [7] but found [57.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [57.0000000001]
at Acacemy.additionTest.AddBracketsFiveAndTwo(additionTest.java:75)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddBracketsFiveAndTwo -->
  <testcase name="AddDecimalTwoPointTwoMinusOne" time="5.271" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [3.2] but found [3.2000000001]">
      <![CDATA[java.lang.AssertionError: expected [3.2] but found [3.2000000001]
at Acacemy.additionTest.AddDecimalTwoPointTwoMinusOne(additionTest.java:82)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddDecimalTwoPointTwoMinusOne -->
  <testcase name="AddMorethanTwoNumbers" time="5.403" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [21] but found [21.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [21] but found [21.0000000001]
at Acacemy.additionTest.AddMorethanTwoNumbers(additionTest.java:61)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddMorethanTwoNumbers -->
  <testcase name="AddOneAndZero" time="5.168" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [8] but found [8.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [8.0000000001]
at Acacemy.additionTest.AddOneAndZero(additionTest.java:68)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddOneAndZero -->
  <testcase name="AddZeroAndOne" time="5.185" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [4] but found [4.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [4.0000000001]
at Acacemy.additionTest.AddZeroAndOne(additionTest.java:50)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddZeroAndOne -->
  <testcase name="AddZeroAndZero" time="5.19" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [2.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [2.0000000001]
at Acacemy.additionTest.AddZeroAndZero(additionTest.java:38)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddZeroAndZero -->
  <testcase name="SubtractAscendRangeAndDescendRange" time="5.684" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [-55545] but found [345622.5000000001]">
      <![CDATA[java.lang.AssertionError: expected [-55545] but found [345622.5000000001]
at Acacemy.SubtractionTest.SubtractAscendRangeAndDescendRange(SubtractionTest.java:39)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractAscendRangeAndDescendRange -->
  <testcase name="SubtractBracketsFiveAndTwo" time="5.242" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [-7] but found [7.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [-7] but found [7.0000000001]
at Acacemy.SubtractionTest.SubtractBracketsFiveAndTwo(SubtractionTest.java:77)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractBracketsFiveAndTwo -->
  <testcase name="SubtractDecimalTwoPointTwoMinusOne" time="5.248" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [3.2] but found [3.2000000001]">
      <![CDATA[java.lang.AssertionError: expected [3.2] but found [3.2000000001]
at Acacemy.SubtractionTest.SubtractDecimalTwoPointTwoMinusOne(SubtractionTest.java:84)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractDecimalTwoPointTwoMinusOne -->
  <testcase name="SubtractMorethanTwoNumbers" time="5.29" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [15.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [15.0000000001]
at Acacemy.SubtractionTest.SubtractMorethanTwoNumbers(SubtractionTest.java:92)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractMorethanTwoNumbers -->
  <testcase name="SubtractOneAndZero" time="5.169" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [-6] but found [8.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [-6] but found [8.0000000001]
at Acacemy.SubtractionTest.SubtractOneAndZero(SubtractionTest.java:70)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractOneAndZero -->
  <testcase name="SubtractZeroAndOne" time="5.16" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [4.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [4.0000000001]
at Acacemy.SubtractionTest.SubtractZeroAndOne(SubtractionTest.java:59)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractZeroAndOne -->
  <testcase name="SubtractZeroAndZero" time="5.156" classname="Acacemy.SubtractionTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2.0000000001]
at Acacemy.SubtractionTest.SubtractZeroAndZero(SubtractionTest.java:47)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- SubtractZeroAndZero -->
  <testcase name="VerifyingElements" time="5.139" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="clear" time="5.076" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="divide" time="5.104" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="minus" time="5.142" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="multiply" time="5.116" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="number0" time="5.12" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="number2" time="5.102" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="number3" time="5.111" classname="Acacemy.VerifyingElementsareClickable"/>
  <testcase name="number4" time="5.065" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [4] but found [44]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [44]
at Acacemy.VerifyingElementsareClickable.number4(VerifyingElementsareClickable.java:71)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- number4 -->
  <testcase name="number5" time="5.061" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [5] but found [445]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [445]
at Acacemy.VerifyingElementsareClickable.number5(VerifyingElementsareClickable.java:78)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- number5 -->
  <testcase name="number6" time="5.08" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [6] but found [4456]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [4456]
at Acacemy.VerifyingElementsareClickable.number6(VerifyingElementsareClickable.java:85)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- number6 -->
  <testcase name="number7" time="5.063" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [7] but found [44567]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [44567]
at Acacemy.VerifyingElementsareClickable.number7(VerifyingElementsareClickable.java:92)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- number7 -->
  <testcase name="number8" time="5.098" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [8] but found [445678]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [445678]
at Acacemy.VerifyingElementsareClickable.number8(VerifyingElementsareClickable.java:99)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- number8 -->
  <testcase name="number9" time="5.072" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [9] but found [4456789]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [4456789]
at Acacemy.VerifyingElementsareClickable.number9(VerifyingElementsareClickable.java:106)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- number9 -->
  <testcase name="plus" time="5.072" classname="Acacemy.VerifyingElementsareClickable">
    <failure type="java.lang.AssertionError" message="expected [+] but found [4456789+]">
      <![CDATA[java.lang.AssertionError: expected [+] but found [4456789+]
at Acacemy.VerifyingElementsareClickable.plus(VerifyingElementsareClickable.java:113)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- plus -->
  <testcase name="DivideAscendRangeAndDescendRange" time="5.619" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [0.1818382677861246] but found [0.9084180292648255]">
      <![CDATA[java.lang.AssertionError: expected [0.1818382677861246] but found [0.9084180292648255]
at Acacemy.DivisionTests.DivideAscendRangeAndDescendRange(DivisionTests.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideAscendRangeAndDescendRange -->
  <testcase name="DivideDecimalTwoPointTwoMinusOne" time="5.308" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [0.45] but found [0.4500000001]">
      <![CDATA[java.lang.AssertionError: expected [0.45] but found [0.4500000001]
at Acacemy.DivisionTests.DivideDecimalTwoPointTwoMinusOne(DivisionTests.java:81)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideDecimalTwoPointTwoMinusOne -->
  <testcase name="DivideMorethanTwoNumbers" time="5.314" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [11.916666666766666] but found [10.856060606160606]">
      <![CDATA[java.lang.AssertionError: expected [11.916666666766666] but found [10.856060606160606]
at Acacemy.DivisionTests.DivideMorethanTwoNumbers(DivisionTests.java:37)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideMorethanTwoNumbers -->
  <testcase name="DivideNegativeandPostiveNumbers" time="5.282" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [-1.4] but found [1.4000000001]">
      <![CDATA[java.lang.AssertionError: expected [-1.4] but found [1.4000000001]
at Acacemy.DivisionTests.DivideNegativeandPostiveNumbers(DivisionTests.java:74)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideNegativeandPostiveNumbers -->
  <testcase name="DivideOneAndZero" time="5.179" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [Infinity] but found [&amp;quot;Infinity&amp;quot;]">
      <![CDATA[java.lang.AssertionError: expected [Infinity] but found ["Infinity"]
at Acacemy.DivisionTests.DivideOneAndZero(DivisionTests.java:67)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideOneAndZero -->
  <testcase name="DivideZeroAndOne" time="5.166" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.DivisionTests.DivideZeroAndOne(DivisionTests.java:56)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideZeroAndOne -->
  <testcase name="DivideZeroAndZero" time="5.194" classname="Acacemy.DivisionTests">
    <failure type="java.lang.AssertionError" message="expected [NaN] but found [&amp;quot;NaN&amp;quot;]">
      <![CDATA[java.lang.AssertionError: expected [NaN] but found ["NaN"]
at Acacemy.DivisionTests.DivideZeroAndZero(DivisionTests.java:44)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- DivideZeroAndZero -->
  <testcase name="MultiplyAscendRangeAndDescendRange" time="5.601" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [38102050] but found [4.122551025E9]">
      <![CDATA[java.lang.AssertionError: expected [38102050] but found [4.122551025E9]
at Acacemy.multiplicationTests.MultiplyAscendRangeAndDescendRange(multiplicationTests.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyAscendRangeAndDescendRange -->
  <testcase name="MultiplyDecimalTwoPointTwoMinusOne" time="5.301" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [11.25] but found [11.2500000001]">
      <![CDATA[java.lang.AssertionError: expected [11.25] but found [11.2500000001]
at Acacemy.multiplicationTests.MultiplyDecimalTwoPointTwoMinusOne(multiplicationTests.java:81)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyDecimalTwoPointTwoMinusOne -->
  <testcase name="MultiplyMorethanTwoNumbers" time="5.293" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [216] but found [2376.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [216] but found [2376.0000000001]
at Acacemy.multiplicationTests.MultiplyMorethanTwoNumbers(multiplicationTests.java:37)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyMorethanTwoNumbers -->
  <testcase name="MultiplyNegativeandPostiveNumbers" time="5.261" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [-35] but found [35.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [-35] but found [35.0000000001]
at Acacemy.multiplicationTests.MultiplyNegativeandPostiveNumbers(multiplicationTests.java:74)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyNegativeandPostiveNumbers -->
  <testcase name="MultiplyOneAndZero" time="5.179" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.multiplicationTests.MultiplyOneAndZero(multiplicationTests.java:67)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyOneAndZero -->
  <testcase name="MultiplyZeroAndOne" time="5.208" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.multiplicationTests.MultiplyZeroAndOne(multiplicationTests.java:56)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyZeroAndOne -->
  <testcase name="MultiplyZeroAndZero" time="5.208" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.multiplicationTests.MultiplyZeroAndZero(multiplicationTests.java:44)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyZeroAndZero -->
</testsuite> <!-- HomePage -->
